/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAddItemOfSell.java
 *
 * Created on Aug 20, 2008, 9:35:56 AM
 */

package br.com.agrofacil.frames;

import br.com.agrofacil.dao.EquipamentoDAO;
import br.com.agrofacil.entity.ApontamentoInsumoItem;
import br.com.agrofacil.entity.ApontamentoPlantioItem2;
import br.com.agrofacil.entity.Equipamento;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dyego
 */
public class FrmAddApontamentoPlantioItem2 extends javax.swing.JDialog {

    private final List<ApontamentoPlantioItem2> itens;
    private FrmAddApontamentoPlantio apontPlantioForm;
    private FrmUpdateApontamentoPlantio apontInsumoFormUp;
    
    private final EquipamentoDAO equipamento = new EquipamentoDAO();
    //private frmUpdateSell updateForm;
    /** Creates new form frmAddItemOfSell */
    public FrmAddApontamentoPlantioItem2(java.awt.Frame parent, boolean modal,List<ApontamentoPlantioItem2> itens,FrmAddApontamentoPlantio apontPlantioForm) throws SQLException {
        super(parent, modal);
        this.itens = itens;
        this.apontPlantioForm = apontPlantioForm;
        initComponents();
        loadComboData();
    }
    
     public FrmAddApontamentoPlantioItem2(java.awt.Frame parent, boolean modal,List<ApontamentoPlantioItem2> itens,FrmUpdateApontamentoPlantio apontInsumoFormUp) throws SQLException {
        super(parent, modal);
        this.itens = itens;
        this.apontInsumoFormUp = apontInsumoFormUp;
        initComponents();
        loadComboData();
    }   

    /*
    public FrmAddApontamentoInsumoItem(JFrame parent, boolean modal, List<ApontamentoInsumoItem> itens, frmUpdateSell updateForm) {
        super(parent, modal);
        this.itens = itens;
        this.updateForm = updateForm;
        initComponents();
        loadComboData();
    }
    * /

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDescricao4 = new javax.swing.JLabel();
        cbEquipamento = new javax.swing.JComboBox();
        btnProducrar2 = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox();
        lblDescricao5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Item");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDescricao4.setText("Equipamento");

        btnProducrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar2.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar2ActionPerformed(evt);
            }
        });

        btOk.setText("Adicionar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("Descricao");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "CG", "TR", "TT", "CD" }));

        lblDescricao5.setText("Tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao4)
                            .addComponent(jLabel8)
                            .addComponent(lblDescricao5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEquipamento, 0, 327, Short.MAX_VALUE)
                                    .addComponent(txtDescricao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao4)
                        .addComponent(cbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao5)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(503, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar2ActionPerformed
        FrmPesquisaEquipamento dialog = new FrmPesquisaEquipamento(cbEquipamento);
    }//GEN-LAST:event_btnProducrar2ActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        
        if (cbEquipamento.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Equipamento Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Descrição Não Informada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }      
        
        int opt = JOptionPane.showConfirmDialog(this,"Você tem Certeza ?","Adicionar Novo Item",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (opt == 0) {         
           ApontamentoPlantioItem2 item = new ApontamentoPlantioItem2();
           item.setEquipamento((Equipamento) cbEquipamento.getSelectedItem()); 
           item.setDescricao(txtDescricao.getText());
           item.setTipo(cbTipo.getSelectedItem().toString());
           
           itens.add(item);

           if (apontPlantioForm != null) {
               apontPlantioForm.refreshItens();
           } else {
               apontInsumoFormUp.refreshItens();
           }
           setVisible(false);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar2;
    private javax.swing.JComboBox cbEquipamento;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables

    private void loadComboData() throws SQLException {
        /*
           List<Equipamento> equipamento = new EquipamentoDAO().getAllEquipamento();
           DefaultComboBoxModel dcbmEquip = new DefaultComboBoxModel(new Vector<Equipamento>(equipamento));
           cbEquipamento.setModel(dcbmEquip);
           */
    }

}
