package br.com.agrofacil.frames;


import br.com.agrofacil.dao.ApontamentoManualDAO;
import br.com.agrofacil.dao.CentroCustoDAO;
import br.com.agrofacil.dao.EquipamentoDAO;
import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.FrenteTransporteDAO;
import br.com.agrofacil.dao.FuncionarioDAO;
import br.com.agrofacil.dao.OperacaoDAO;
import br.com.agrofacil.dao.SafraDAO;
import br.com.agrofacil.dao.SetorDAO;
import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.entity.ApontamentoManual;
import br.com.agrofacil.entity.CentroCusto;
import br.com.agrofacil.entity.Equipamento;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.FrenteTransporte;
import br.com.agrofacil.entity.Funcionario;
import br.com.agrofacil.entity.Operacao;
import br.com.agrofacil.entity.Safra;
import br.com.agrofacil.entity.Setor;
import br.com.agrofacil.entity.Talhao;
import br.com.agrofacil.entity.TipoPlantioColheita;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kelson
 */
public class FrmAddApontamentoManual extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private final ApontamentoManualDAO dao;
    private final FrmApontamentoManual control;
    
    private final FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    private final CentroCustoDAO centroDAO = new CentroCustoDAO();
    private final OperacaoDAO operacaoDAO = new OperacaoDAO();    
    private final FrenteTransporteDAO frenteDAO = new FrenteTransporteDAO();    
    private final SafraDAO safraDAO = new SafraDAO();
    private final FazendaDAO fazendaDAO = new FazendaDAO();
    private final SetorDAO setorDAO = new SetorDAO();
    private final TalhaoDAO talhaoDAO = new TalhaoDAO();
    
    public FrmAddApontamentoManual(javax.swing.JDesktopPane parent, boolean modal,ApontamentoManualDAO dao, FrmApontamentoManual control) throws SQLException {             
        this.dao = dao;
        this.control = control;
        this.setTitle("Adicionar Apontamento Manual");
        initComponents();
        initMyComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        cbCentro = new javax.swing.JComboBox();
        lblDescricao1 = new javax.swing.JLabel();
        btnProducrar = new javax.swing.JButton();
        lblDescricao2 = new javax.swing.JLabel();
        cbOperacao = new javax.swing.JComboBox();
        btnProducrar1 = new javax.swing.JButton();
        lblDescricao4 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox();
        btnProducrar2 = new javax.swing.JButton();
        lblDescricao3 = new javax.swing.JLabel();
        cbFrente = new javax.swing.JComboBox();
        btnProducrar3 = new javax.swing.JButton();
        lblDescricao5 = new javax.swing.JLabel();
        cbSafra = new javax.swing.JComboBox();
        btnProducrar4 = new javax.swing.JButton();
        lblDescricao6 = new javax.swing.JLabel();
        cbFazenda = new javax.swing.JComboBox();
        btnProducrar5 = new javax.swing.JButton();
        lblDescricao7 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox();
        btnProducrar6 = new javax.swing.JButton();
        lblDescricao8 = new javax.swing.JLabel();
        cbTalhao = new javax.swing.JComboBox();
        btnProducrar7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtDataOperacao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoraInicial = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraFinal = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHorasTotais = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHorasExtras = new javax.swing.JFormattedTextField();
        txtQtdProd = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(400, 249));

        btOk.setText("Adicionar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblDescricao1.setText("Centro Custo");

        btnProducrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrarActionPerformed(evt);
            }
        });

        lblDescricao2.setText("Operacao");

        btnProducrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar1.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar1ActionPerformed(evt);
            }
        });

        lblDescricao4.setText("Funcionario");

        btnProducrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar2.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar2ActionPerformed(evt);
            }
        });

        lblDescricao3.setText("Frente");

        btnProducrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar3.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar3ActionPerformed(evt);
            }
        });

        lblDescricao5.setText("Safra");

        btnProducrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar4.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar4ActionPerformed(evt);
            }
        });

        lblDescricao6.setText("Fazenda");

        btnProducrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar5.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar5ActionPerformed(evt);
            }
        });

        lblDescricao7.setText("Setor");

        btnProducrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar6.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar6ActionPerformed(evt);
            }
        });

        lblDescricao8.setText("Talhao");

        btnProducrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar7.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Qtd Producao");

        lblDescricao.setText("Data Operação:");

        try {
            txtDataOperacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Hora Inicial");

        txtHoraInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        jLabel6.setText("Hora Final");

        txtHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        jLabel7.setText("Horas Totais");

        txtHorasTotais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        jLabel8.setText("Horas Extras");

        txtHorasExtras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm"))));

        txtQtdProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSafra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbOperacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbCentro, 0, 268, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnProducrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDescricao3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDescricao6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDescricao8)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbTalhao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnProducrar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnProducrar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDataOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao1)
                            .addComponent(cbCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao4)
                            .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao2)
                        .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao3)
                        .addComponent(cbFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao5)
                        .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao6)
                        .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao7)
                        .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao8)
                        .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDataOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtHorasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar7ActionPerformed
        FrmPesquisaTalhao dialog = new FrmPesquisaTalhao(cbTalhao);
    }//GEN-LAST:event_btnProducrar7ActionPerformed

    private void btnProducrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar6ActionPerformed
        FrmPesquisaSetor dialog = new FrmPesquisaSetor(cbSetor);
    }//GEN-LAST:event_btnProducrar6ActionPerformed

    private void btnProducrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar5ActionPerformed
        FrmPesquisaFazenda dialog = new FrmPesquisaFazenda(cbFazenda);
    }//GEN-LAST:event_btnProducrar5ActionPerformed

    private void btnProducrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar4ActionPerformed

    private void btnProducrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar3ActionPerformed
        //FrmPesquisaOperacao dialog = new FrmPes(cbFrente);
    }//GEN-LAST:event_btnProducrar3ActionPerformed

    private void btnProducrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar2ActionPerformed

    private void btnProducrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar1ActionPerformed
        FrmPesquisaOperacao dialog = new FrmPesquisaOperacao(cbOperacao);
    }//GEN-LAST:event_btnProducrar1ActionPerformed

    private void btnProducrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrarActionPerformed
        FrmPesquisaMunicipio dialog = new FrmPesquisaMunicipio(cbCentro);
    }//GEN-LAST:event_btnProducrarActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        ApontamentoManual apont = new ApontamentoManual();

        try {
            
            DateFormat dffrom = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataOperacao = new java.sql.Date(dffrom.parse(txtDataOperacao.getText()).getTime());
            
            apont.setCentroCusto((CentroCusto) cbCentro.getSelectedItem());
            apont.setOperacao((Operacao) cbOperacao.getSelectedItem());
            apont.setFuncionario((Funcionario) cbFuncionario.getSelectedItem());
            apont.setFrente((FrenteTransporte) cbFrente.getSelectedItem());
            apont.setSafra((Safra) cbSafra.getSelectedItem());
            apont.setFazenda((Fazenda) cbFazenda.getSelectedItem());
            apont.setSetor((Setor) cbSetor.getSelectedItem());
            apont.setTalhao((Talhao) cbTalhao.getSelectedItem());                 
            apont.setHoraInicial(txtHoraInicial.getText());
            apont.setHoraFinal(txtHoraFinal.getText());
            apont.setHorasTotais(txtHorasTotais.getText());
            apont.setHorasExtras(txtHorasExtras.getText());
            apont.setQtdProducao(Float.parseFloat(txtQtdProd.getText().replace(",", ".")));
            apont.setDataOperacao(dataOperacao);
            
            int result = JOptionPane.showConfirmDialog(this, "Você Tem Certeza ??","Adicionar Apontamento Manual",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(result != 0) {
                return;
            }

            dao.addApontamentoManual(apont);

            control.loadInitialData();
            setVisible(false);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar Apontamento Manual "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOkActionPerformed

private void initMyComponents() throws SQLException {  
   
    this.btOk.setIcon(new ImageIcon("icons/check16.png"));
    this.btCancel.setIcon(new ImageIcon("icons/cancel16.png"));
   
   /* 
   List<CentroCusto> centro = new CentroCustoDAO().getAllCentroCusto();
   DefaultComboBoxModel dcbmCentro = new DefaultComboBoxModel(new Vector<CentroCusto>(centro));
   cbCentro.setModel(dcbmCentro);
   
   List<Operacao> operacao = new OperacaoDAO().getAllOperacao();
   DefaultComboBoxModel dcbmOperacao = new DefaultComboBoxModel(new Vector<Operacao>(operacao));
   cbOperacao.setModel(dcbmOperacao);
   
   List<Funcionario> funcionario = new FuncionarioDAO().getAllFuncionario();
   DefaultComboBoxModel dcbmFuncionario = new DefaultComboBoxModel(new Vector<Funcionario>(funcionario));
   cbFuncionario.setModel(dcbmFuncionario);  
   
   List<FrenteTransporte> frente = new FrenteTransporteDAO().getAllFrenteTransporte();
   DefaultComboBoxModel dcbmFrente = new DefaultComboBoxModel(new Vector<FrenteTransporte>(frente));
   cbFrente.setModel(dcbmFrente);
   */
   List<Safra> safra = new SafraDAO().getAllSafra();
   DefaultComboBoxModel dcbmSafra = new DefaultComboBoxModel(new Vector<Safra>(safra));
   cbSafra.setModel(dcbmSafra);  
   /*
   List<Fazenda> fazenda = new FazendaDAO().getAllFazenda();
   DefaultComboBoxModel dcbmFazenda = new DefaultComboBoxModel(new Vector<Fazenda>(fazenda));
   cbFazenda.setModel(dcbmFazenda);
   
   List<Setor> setor = new SetorDAO().getAllSetor();
   DefaultComboBoxModel dcbmSetor = new DefaultComboBoxModel(new Vector<Setor>(setor));
   cbSetor.setModel(dcbmSetor);
   
   List<Talhao> talhao = new TalhaoDAO().getAllTalhao();
   DefaultComboBoxModel dcbmTalhao = new DefaultComboBoxModel(new Vector<Talhao>(talhao));
   cbTalhao.setModel(dcbmTalhao);
  */   
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar;
    private javax.swing.JButton btnProducrar1;
    private javax.swing.JButton btnProducrar2;
    private javax.swing.JButton btnProducrar3;
    private javax.swing.JButton btnProducrar4;
    private javax.swing.JButton btnProducrar5;
    private javax.swing.JButton btnProducrar6;
    private javax.swing.JButton btnProducrar7;
    private javax.swing.JComboBox cbCentro;
    private javax.swing.JComboBox cbFazenda;
    private javax.swing.JComboBox cbFrente;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbOperacao;
    private javax.swing.JComboBox cbSafra;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JComboBox cbTalhao;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    private javax.swing.JFormattedTextField txtDataOperacao;
    private javax.swing.JFormattedTextField txtHoraFinal;
    private javax.swing.JFormattedTextField txtHoraInicial;
    private javax.swing.JFormattedTextField txtHorasExtras;
    private javax.swing.JFormattedTextField txtHorasTotais;
    private javax.swing.JFormattedTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables


}
