package br.com.agrofacil.frames;


import br.com.agrofacil.dao.EmpresaDAO;
import br.com.agrofacil.dao.EspacamentoDAO;
import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.FrenteTransporteDAO;
import br.com.agrofacil.dao.ObjetivoSafraDAO;
import br.com.agrofacil.dao.SafraDAO;
import br.com.agrofacil.dao.SetorDAO;
import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.dao.UnidadeIndustrialDAO;
import br.com.agrofacil.dao.VariedadeDAO;
import br.com.agrofacil.entity.Empresa;
import br.com.agrofacil.entity.Espacamento;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.FrenteTransporte;
import br.com.agrofacil.entity.HistoricoSafra;
import br.com.agrofacil.entity.ObjetivoSafra;
import br.com.agrofacil.entity.Safra;
import br.com.agrofacil.entity.Setor;
import br.com.agrofacil.entity.Talhao;
import br.com.agrofacil.entity.TipoPlantioColheita;
import br.com.agrofacil.entity.TipoPropriedade;
import br.com.agrofacil.entity.UnidadeIndustrial;
import br.com.agrofacil.entity.Variedade;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kelson
 */
public class FrmAddObjetivoSafra extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private final ObjetivoSafraDAO dao;
    private final FrmObjetivoSafra control;
    
    private final SafraDAO safraDAO = new SafraDAO();
    private final FazendaDAO fazendaDAO = new FazendaDAO();
    private final SetorDAO setorDAO = new SetorDAO();
    private final TalhaoDAO talhaoDAO = new TalhaoDAO();
    private final FrenteTransporteDAO frenteDAO = new FrenteTransporteDAO();
    private final VariedadeDAO variedadeDAO = new VariedadeDAO();
    private final EspacamentoDAO espacamentoDAO = new EspacamentoDAO();
    private final EmpresaDAO empresaDAO = new EmpresaDAO();
    private final UnidadeIndustrialDAO unidadeIndDAO = new UnidadeIndustrialDAO();
    
    
    
    public FrmAddObjetivoSafra(javax.swing.JDesktopPane parent, boolean modal,ObjetivoSafraDAO dao, FrmObjetivoSafra control) throws SQLException {             
        this.dao = dao;
        this.control = control;
        this.setTitle("Adicionar Objetivo de Safra");
        initComponents();
        initMyComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lblDescricao10 = new javax.swing.JLabel();
        cbHistorico = new javax.swing.JComboBox();
        lblDescricao3 = new javax.swing.JLabel();
        cbFrente = new javax.swing.JComboBox();
        btnProducrar3 = new javax.swing.JButton();
        lblDescricao5 = new javax.swing.JLabel();
        cbSafra = new javax.swing.JComboBox();
        btnProducrar4 = new javax.swing.JButton();
        lblDescricao6 = new javax.swing.JLabel();
        cbFazenda = new javax.swing.JComboBox();
        btnProducrar5 = new javax.swing.JButton();
        lblDescricao7 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox();
        btnProducrar6 = new javax.swing.JButton();
        lblDescricao8 = new javax.swing.JLabel();
        cbTalhao = new javax.swing.JComboBox();
        btnProducrar7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDistTerra = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAsfalto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAreaProd = new javax.swing.JFormattedTextField();
        txtHidrovia = new javax.swing.JFormattedTextField();
        lblDescricao2 = new javax.swing.JLabel();
        txtDataHIstorico = new javax.swing.JFormattedTextField();
        lblDescricao11 = new javax.swing.JLabel();
        cbTipoPropriedade = new javax.swing.JComboBox();
        lblDescricao12 = new javax.swing.JLabel();
        cbTipoColheita = new javax.swing.JComboBox();
        btnProducrar8 = new javax.swing.JButton();
        cbVariedade = new javax.swing.JComboBox();
        lblDescricao9 = new javax.swing.JLabel();
        lblDescricao13 = new javax.swing.JLabel();
        cbEspacamento = new javax.swing.JComboBox();
        btnProducrar9 = new javax.swing.JButton();
        lblDescricao14 = new javax.swing.JLabel();
        cbTipoPlantio = new javax.swing.JComboBox();
        lblDescricao15 = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox();
        btnProducrar10 = new javax.swing.JButton();
        lblDescricao16 = new javax.swing.JLabel();
        cbUnidadeInd = new javax.swing.JComboBox();
        btnProducrar11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtThc = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(400, 249));

        btOk.setText("Adicionar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblDescricao10.setText("Historico");

        cbHistorico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescricao3.setText("Frente");

        btnProducrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar3.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar3ActionPerformed(evt);
            }
        });

        lblDescricao5.setText("Safra");

        btnProducrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar4.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar4ActionPerformed(evt);
            }
        });

        lblDescricao6.setText("Fazenda");

        btnProducrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar5.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar5ActionPerformed(evt);
            }
        });

        lblDescricao7.setText("Setor");

        btnProducrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar6.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar6ActionPerformed(evt);
            }
        });

        lblDescricao8.setText("Talhao");

        btnProducrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar7.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Dist Terra");

        txtDistTerra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setText("Dist Asfalto");

        txtAsfalto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setText("Dist Hidrovia");

        jLabel5.setText("Area Prod");

        lblDescricao2.setText("Data Historico");

        try {
            txtDataHIstorico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao11.setText("Tipo Propriedade");

        cbTipoPropriedade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescricao12.setText("Tipo Colheita");

        cbTipoColheita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnProducrar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar8.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar8ActionPerformed(evt);
            }
        });

        lblDescricao9.setText("Variedade");

        lblDescricao13.setText("Espacamento");

        btnProducrar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar9.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar9ActionPerformed(evt);
            }
        });

        lblDescricao14.setText("Tipo Plantio");

        cbTipoPlantio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescricao15.setText("Empresa");

        btnProducrar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar10.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar10ActionPerformed(evt);
            }
        });

        lblDescricao16.setText("Unidade Ind");

        btnProducrar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar11.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar11ActionPerformed(evt);
            }
        });

        jLabel6.setText("Thc");

        jLabel7.setText("Idade");

        txtIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDescricao15)
                        .addGap(10, 10, 10)
                        .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDescricao6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDescricao8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDescricao3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbFrente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnProducrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtDistTerra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsfalto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel4)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtHidrovia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAreaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtThc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbVariedade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnProducrar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDataHIstorico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDescricao11)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbTipoPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDescricao12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbTipoColheita, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnProducrar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblDescricao16)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(cbUnidadeInd, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblDescricao13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbEspacamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnProducrar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblDescricao14)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnProducrar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbTipoPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao10)
                                .addComponent(cbHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao5)
                                .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao6)
                                .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao7)
                                .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao8)
                                .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao3)
                                .addComponent(cbFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao2)
                            .addComponent(txtDataHIstorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao11)
                            .addComponent(cbTipoPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao12)
                            .addComponent(cbTipoColheita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao9)
                                .addComponent(cbVariedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao13)
                                .addComponent(cbEspacamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao14)
                        .addComponent(cbTipoPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao15)
                        .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao16)
                        .addComponent(cbUnidadeInd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtAreaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtThc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDistTerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtAsfalto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtHidrovia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar7ActionPerformed

    private void btnProducrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar6ActionPerformed

    private void btnProducrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar5ActionPerformed

    private void btnProducrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar4ActionPerformed

    private void btnProducrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar3ActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        ObjetivoSafra objetivoSafra = new ObjetivoSafra();

        try {
            DateFormat dffrom = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataHistorico = new java.sql.Date(dffrom.parse(txtDataHIstorico.getText()).getTime());
            
            objetivoSafra.setHistorico(HistoricoSafra.valueOf(cbHistorico.getSelectedItem().toString()));            
            objetivoSafra.setSafra((Safra) cbSafra.getSelectedItem());
            objetivoSafra.setFazenda((Fazenda) cbFazenda.getSelectedItem());
            objetivoSafra.setSetor((Setor) cbSetor.getSelectedItem());
            objetivoSafra.setTalhao((Talhao) cbTalhao.getSelectedItem());            
            objetivoSafra.setDataHistorico(dataHistorico);
            objetivoSafra.setTipropriedade(TipoPropriedade.valueOf(cbTipoPropriedade.getSelectedItem().toString()));                        
            objetivoSafra.setFrente((FrenteTransporte) cbFrente.getSelectedItem());
            objetivoSafra.setTipoColheita(TipoPlantioColheita.valueOf(cbTipoColheita.getSelectedItem().toString()));
            objetivoSafra.setVariedade((Variedade) cbVariedade.getSelectedItem());
            objetivoSafra.setEspacamento((Espacamento) cbEspacamento.getSelectedItem());
            objetivoSafra.setTipoPlantio(TipoPlantioColheita.valueOf(cbTipoPlantio.getSelectedItem().toString()));
            objetivoSafra.setEmpresa((Empresa) cbEmpresa.getSelectedItem());
            objetivoSafra.setUnidadeIndustrial((UnidadeIndustrial) cbUnidadeInd.getSelectedItem());
            objetivoSafra.setIdade(Integer.parseInt(txtIdade.getText()));
            objetivoSafra.setDistTerra(Integer.parseInt(txtDistTerra.getText()));
            objetivoSafra.setDistAsfalto(Integer.parseInt(txtAsfalto.getText()));            
            objetivoSafra.setDistHidrovia(Float.parseFloat(txtHidrovia.getText()));
            objetivoSafra.setAreaProdutiva(Float.parseFloat(txtAreaProd.getText()));
            objetivoSafra.setThc(Float.parseFloat(txtThc.getText()));
            
            int result = JOptionPane.showConfirmDialog(this, "Você Tem Certeza ??","Adicionar Objetivo de Safra",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(result != 0) {
                return;
            }

            dao.addObjetivoSafra(objetivoSafra);

            control.loadInitialData();
            setVisible(false);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar Objetivo de Safra "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btnProducrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar8ActionPerformed

    private void btnProducrar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar9ActionPerformed

    private void btnProducrar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar10ActionPerformed

    private void btnProducrar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducrar11ActionPerformed

private void initMyComponents() throws SQLException {  
   
    this.btOk.setIcon(new ImageIcon("icons/check16.png"));
    this.btCancel.setIcon(new ImageIcon("icons/cancel16.png"));
   
   List<FrenteTransporte> frente = new FrenteTransporteDAO().getAllFrenteTransporte();
   DefaultComboBoxModel dcbmFrente = new DefaultComboBoxModel(new Vector<FrenteTransporte>(frente));
   cbFrente.setModel(dcbmFrente);
   
   List<Safra> safra = new SafraDAO().getAllSafra();
   DefaultComboBoxModel dcbmSafra = new DefaultComboBoxModel(new Vector<Safra>(safra));
   cbSafra.setModel(dcbmSafra);  

   List<Fazenda> fazenda = new FazendaDAO().getAllFazenda();
   DefaultComboBoxModel dcbmFazenda = new DefaultComboBoxModel(new Vector<Fazenda>(fazenda));
   cbFazenda.setModel(dcbmFazenda);
   
   List<Setor> setor = new SetorDAO().getAllSetor();
   DefaultComboBoxModel dcbmSetor = new DefaultComboBoxModel(new Vector<Setor>(setor));
   cbSetor.setModel(dcbmSetor);
   
   List<Talhao> talhao = new TalhaoDAO().getAllTalhao();
   DefaultComboBoxModel dcbmTalhao = new DefaultComboBoxModel(new Vector<Talhao>(talhao));
   cbTalhao.setModel(dcbmTalhao);
   
   List<Empresa> empresa = new EmpresaDAO().getAllEmpresa();
   DefaultComboBoxModel dcbmEmpresa = new DefaultComboBoxModel(new Vector<Empresa>(empresa));
   cbEmpresa.setModel(dcbmEmpresa);
   
   List<UnidadeIndustrial> unidadeInd = new UnidadeIndustrialDAO().getAllUnidadeIndustrial();
   DefaultComboBoxModel dcbmUnidadeInd = new DefaultComboBoxModel(new Vector<UnidadeIndustrial>(unidadeInd));
   cbUnidadeInd.setModel(dcbmUnidadeInd);
   
   List<Variedade> variedade = new VariedadeDAO().getAllVariedade();
   DefaultComboBoxModel dcbmVariedade = new DefaultComboBoxModel(new Vector<Variedade>(variedade));
   cbVariedade.setModel(dcbmVariedade);
   
   List<Espacamento> espacamento = new EspacamentoDAO().getAllEspacamento();
   DefaultComboBoxModel dcbmEspacamento = new DefaultComboBoxModel(new Vector<Espacamento>(espacamento));
   cbEspacamento.setModel(dcbmEspacamento);   
   
   cbHistorico.setModel(new DefaultComboBoxModel<>(HistoricoSafra.values()));
   cbTipoColheita.setModel(new DefaultComboBoxModel<>(TipoPlantioColheita.values()));
   cbTipoPlantio.setModel(new DefaultComboBoxModel<>(TipoPlantioColheita.values()));
   cbTipoPropriedade.setModel(new DefaultComboBoxModel<>(TipoPropriedade.values()));
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar10;
    private javax.swing.JButton btnProducrar11;
    private javax.swing.JButton btnProducrar3;
    private javax.swing.JButton btnProducrar4;
    private javax.swing.JButton btnProducrar5;
    private javax.swing.JButton btnProducrar6;
    private javax.swing.JButton btnProducrar7;
    private javax.swing.JButton btnProducrar8;
    private javax.swing.JButton btnProducrar9;
    private javax.swing.JComboBox cbEmpresa;
    private javax.swing.JComboBox cbEspacamento;
    private javax.swing.JComboBox cbFazenda;
    private javax.swing.JComboBox cbFrente;
    private javax.swing.JComboBox cbHistorico;
    private javax.swing.JComboBox cbSafra;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JComboBox cbTalhao;
    private javax.swing.JComboBox cbTipoColheita;
    private javax.swing.JComboBox cbTipoPlantio;
    private javax.swing.JComboBox cbTipoPropriedade;
    private javax.swing.JComboBox cbUnidadeInd;
    private javax.swing.JComboBox cbVariedade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricao10;
    private javax.swing.JLabel lblDescricao11;
    private javax.swing.JLabel lblDescricao12;
    private javax.swing.JLabel lblDescricao13;
    private javax.swing.JLabel lblDescricao14;
    private javax.swing.JLabel lblDescricao15;
    private javax.swing.JLabel lblDescricao16;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    private javax.swing.JLabel lblDescricao9;
    private javax.swing.JFormattedTextField txtAreaProd;
    private javax.swing.JFormattedTextField txtAsfalto;
    private javax.swing.JFormattedTextField txtDataHIstorico;
    private javax.swing.JFormattedTextField txtDistTerra;
    private javax.swing.JFormattedTextField txtHidrovia;
    private javax.swing.JFormattedTextField txtIdade;
    private javax.swing.JFormattedTextField txtThc;
    // End of variables declaration//GEN-END:variables


}
