package br.com.agrofacil.frames;


import br.com.agrofacil.dao.ApontamentoInsumoDAO;
import br.com.agrofacil.entity.ApontamentoInsumo;
import br.com.agrofacil.entity.ApontamentoInsumoItem;
import br.com.agrofacil.util.TableColumnAdjuster;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kelson
 */
public class FrmApontamentoInsumo2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    
    private final ApontamentoInsumoDAO dao = new ApontamentoInsumoDAO();
    private List<ApontamentoInsumo> apontamento = new LinkedList<>();
    private List<ApontamentoInsumoItem> itens = new LinkedList<>();
    private FrmPrincipal main;
    
    public FrmApontamentoInsumo2(FrmPrincipal main) throws SQLException {
        this.main = main;
        this.setTitle("Manutenção - Apontamento de Insumo");
        this.setResizable(false);
        this.setClosable(false);
        this.setMaximizable(false);        
        initComponents();        
        initMyComponents();
        loadInitialData();
        addSellTableListener();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApontamento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(400, 249));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btAtualizar)
                    .addComponent(btRemover)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        tblApontamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblApontamento);

        jTabbedPane1.addTab("Apontamento Insumos", jScrollPane1);

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblItens);

        jTabbedPane1.addTab("ApontamentoInsumoItens", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
/*
        try {
            
            FrmAddApontamentoInsumo dialog = new FrmAddApontamentoInsumo( new javax.swing.JDesktopPane(), true,dao,this);    
            dialog.setVisible(true);
            dialog.setResizable(false);
            dialog.setClosable(false);        
            dialog.setMaximizable(false);        

            this.main.getDesktopPane().add(dialog);
           try {
               dialog.setMaximum(true);
           } catch (PropertyVetoException ex) {
               Logger.getLogger(FrmApontamentoInsumo.class.getName()).log(Level.SEVERE, null, ex);
           }
        } catch (SQLException ex) {
            Logger.getLogger(FrmApontamentoInsumo.class.getName()).log(Level.SEVERE, null, ex);
        }
  */  
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
/*
        try {                                            
            // TODO add your handling code here:
            if(jTable1.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Selecione Apontamento de Insumo para Editar");
                return;
            }

            FrmUpdateEquipamento dialog = new FrmUpdateEquipamento( new javax.swing.JDesktopPane(), true, equipamento.get(jTable1.getSelectedRow()), dao, this);    
            dialog.setVisible(true);
            dialog.setResizable(false);
            dialog.setClosable(false);
            dialog.setMaximizable(false);        
                        
            this.main.getDesktopPane().add(dialog);
            dialog.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmApontamentoProducao.class.getName()).log(Level.SEVERE, null, ex);
        }
        * */
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        if(tblApontamento.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Escolha Apontamento de Insumo para Remover !!");
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "Você tem Certeza ??","Remover Apontamento de Insumo",JOptionPane.OK_CANCEL_OPTION);

        if(result != 0) {
            return;
        }
        try {
            try {
                dao.deleteApontamentoInsumo(
                        apontamento.get(tblApontamento.getSelectedRow()).getId());
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao Remover Apontamento de Insumo","Remover Apontamento de Insumo",JOptionPane.ERROR_MESSAGE);
            }
            loadInitialData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmApontamentoInsumo2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

   public void loadInitialData() throws SQLException {
       final List<String> columns = new ArrayList<String>();
       final List<String[]> values = new ArrayList<String[]>();      
       
       columns.add("Sequencia");
       columns.add("Dose");
       columns.add("Equipamento");
       columns.add("Vazao");
       columns.add("QtdTotal");
       
    try {
            apontamento = dao.getAllApontamentoInsumo();
            tblApontamento.setModel(new MyTableModel(ApontamentoInsumo.class, apontamento, tblApontamento));
            tblItens.setModel(new MyTableModel(ApontamentoInsumoItem.class,new LinkedList<ApontamentoInsumoItem>() , tblItens));    
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }  
 

       private void addSellTableListener() {
       
       final List<String> columns = new ArrayList<String>();
       final List<String[]> values = new ArrayList<String[]>();      
       
       columns.add("Sequencia");
       columns.add("Dose");
       columns.add("Equipamento");
       columns.add("Vazao");
       columns.add("QtdTotal");
       
       
        tblApontamento.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            
            public void valueChanged(ListSelectionEvent e) {
                try {
                    itens = dao.getApontamentoInsumoItem(apontamento.get(tblApontamento.getSelectedRow()));
                } catch (SQLException ex) {
                    Logger.getLogger(FrmApontamentoInsumo2.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (itens.size() > 0) {
                        values.clear();
                        for (int i = 0; i < itens.size(); i++) {
                            values.add(new String[] {String.valueOf(itens.get(i).getSequencia()),
                                    String.valueOf(itens.get(i).getDoseProgramada()),
                                    itens.get(i).getEquipamento().toString(),
                                    String.valueOf(itens.get(i).getVazaoProgramada()),
                                    String.valueOf(itens.get(i).getQtdTotal()
                                    )});
                        }   
                        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
                        tblItens.setModel(tableModel); 
                        tblItens.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                        TableColumnAdjuster tca = new TableColumnAdjuster(tblItens);
                        tca.setDynamicAdjustment(true);
                        tca.adjustColumns();
                    } 
            }
        });
    }

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblApontamento;
    private javax.swing.JTable tblItens;
    // End of variables declaration//GEN-END:variables

    
    private void initMyComponents() {
        this.btAdicionar.setIcon(new javax.swing.ImageIcon("icons/add2.png"));
        this.btAtualizar.setIcon(new javax.swing.ImageIcon("icons/edit.png"));
        this.btRemover.setIcon(new javax.swing.ImageIcon("icons/delete2.png"));
        this.btVoltar.setIcon(new javax.swing.ImageIcon("icons/exit.png"));
    }
}
