package br.com.agrofacil.frames;


import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.OrdemCorteMudaDAO;
import br.com.agrofacil.dao.SafraDAO;
import br.com.agrofacil.dao.SetorDAO;
import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.dao.VariedadeDAO;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.OrdemCorteMuda;
import br.com.agrofacil.entity.Safra;
import br.com.agrofacil.entity.Setor;
import br.com.agrofacil.entity.Talhao;
import br.com.agrofacil.entity.TipoCorteQueima;
import br.com.agrofacil.entity.TipoPlantioColheita;
import br.com.agrofacil.entity.Variedade;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kelson
 */
public class FrmAddOrdemCorteMuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private final OrdemCorteMudaDAO dao;
    private final FrmOrdemCorteMuda control;
    
    private final FazendaDAO fazendaDAO = new FazendaDAO();
    private final SafraDAO safraDAO = new SafraDAO();
    private final SetorDAO setorDAO = new SetorDAO();
    private final TalhaoDAO talhaoDAO = new TalhaoDAO();
    private final VariedadeDAO variedadeDAO = new VariedadeDAO();
    
    public FrmAddOrdemCorteMuda(javax.swing.JDesktopPane parent, boolean modal,OrdemCorteMudaDAO dao, FrmOrdemCorteMuda control) throws SQLException {             
        this.dao = dao;
        this.control = control;
        this.setTitle("Adicionar Ordem Corte Muda");
        initComponents();
        initMyComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lblDescricao5 = new javax.swing.JLabel();
        cbSafra = new javax.swing.JComboBox();
        lblDescricao6 = new javax.swing.JLabel();
        cbFazenda = new javax.swing.JComboBox();
        btnProducrar5 = new javax.swing.JButton();
        lblDescricao7 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox();
        btnProducrar6 = new javax.swing.JButton();
        lblDescricao8 = new javax.swing.JLabel();
        cbTalhao = new javax.swing.JComboBox();
        btnProducrar7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDescricao10 = new javax.swing.JLabel();
        cbTipoCorte = new javax.swing.JComboBox();
        lblDescricao9 = new javax.swing.JLabel();
        cbVariedade = new javax.swing.JComboBox();
        btnProducrar8 = new javax.swing.JButton();
        lblDescricao11 = new javax.swing.JLabel();
        cbTipoColheita = new javax.swing.JComboBox();
        lblDescricao = new javax.swing.JLabel();
        lblDescricao1 = new javax.swing.JLabel();
        txtQtdArea = new javax.swing.JFormattedTextField();
        txtQtdEsti = new javax.swing.JFormattedTextField();
        txtDataOrdem = new javax.swing.JFormattedTextField();
        txtHoraOrdem = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(400, 249));

        btOk.setText("Adicionar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblDescricao5.setText("Safra");

        lblDescricao6.setText("Fazenda");

        btnProducrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar5.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar5ActionPerformed(evt);
            }
        });

        lblDescricao7.setText("Setor");

        btnProducrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar6.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar6ActionPerformed(evt);
            }
        });

        lblDescricao8.setText("Talhao");

        btnProducrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar7.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Qtd Area Total");

        jLabel5.setText("Qtd Estim Total");

        lblDescricao10.setText("Tipo Corte");

        cbTipoCorte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescricao9.setText("Variedade");

        btnProducrar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar8.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar8ActionPerformed(evt);
            }
        });

        lblDescricao11.setText("Tipo Colheita");

        cbTipoColheita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescricao.setText("Data Ordem");

        lblDescricao1.setText("Hora Ordem");

        txtQtdArea.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtQtdArea.setText("0,00");

        txtQtdEsti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtQtdEsti.setText("0,00");

        try {
            txtDataOrdem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataOrdem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataOrdemFocusGained(evt);
            }
        });

        try {
            txtHoraOrdem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraOrdem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoraOrdemFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblDescricao10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDescricao11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbTipoColheita, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao9)
                            .addComponent(lblDescricao1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbVariedade, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProducrar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHoraOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdArea, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdEsti, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSafra, 0, 316, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(lblDescricao8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(lblDescricao6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbFazenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProducrar7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProducrar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao5)
                        .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao6)
                        .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao7)
                        .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao8))
                    .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao10)
                        .addComponent(cbTipoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao9)
                        .addComponent(cbVariedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao)
                        .addComponent(txtDataOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao11)
                        .addComponent(cbTipoColheita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao1)
                        .addComponent(txtHoraOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtQtdEsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQtdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar7ActionPerformed
        FrmPesquisaTalhao dialog = new FrmPesquisaTalhao(cbTalhao);
    }//GEN-LAST:event_btnProducrar7ActionPerformed

    private void btnProducrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar6ActionPerformed
        FrmPesquisaSetor dialog = new FrmPesquisaSetor(cbSetor);
    }//GEN-LAST:event_btnProducrar6ActionPerformed

    private void btnProducrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar5ActionPerformed
        FrmPesquisaFazenda dialog = new FrmPesquisaFazenda(cbFazenda);
    }//GEN-LAST:event_btnProducrar5ActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        OrdemCorteMuda ordemCorteMuda = new OrdemCorteMuda();

        try {
            DateFormat dffrom = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataOrdem = new java.sql.Date(dffrom.parse(txtDataOrdem.getText()).getTime());
            
            ordemCorteMuda.setSafra((Safra) cbSafra.getSelectedItem());
            ordemCorteMuda.setFazenda((Fazenda) cbFazenda.getSelectedItem());
            ordemCorteMuda.setSetor((Setor) cbSetor.getSelectedItem());
            ordemCorteMuda.setTalhao((Talhao) cbTalhao.getSelectedItem());
            ordemCorteMuda.setVariedade((Variedade) cbVariedade.getSelectedItem());
            ordemCorteMuda.setTipoColheita(TipoPlantioColheita.valueOf(cbTipoColheita.getSelectedItem().toString()));
            ordemCorteMuda.setTipoCorte(TipoCorteQueima.valueOf(cbTipoCorte.getSelectedItem().toString()));
            ordemCorteMuda.setDataOrdem(dataOrdem);
            ordemCorteMuda.setHoraOrdem(txtHoraOrdem.getText());
            ordemCorteMuda.setQtdAreaTotal(Float.parseFloat(txtQtdArea.getText().replace(",", ".")));
            ordemCorteMuda.setQtdEstTotal(Float.parseFloat(txtQtdEsti.getText().replace(",", ".")));
            
            int result = JOptionPane.showConfirmDialog(this, "Você Tem Certeza ??","Adicionar Ordem Corte Muda",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(result != 0) {
                return;
            }

            dao.addOrdemCorteMuda(ordemCorteMuda);

            control.loadInitialData();
            setVisible(false);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar Ordem Corte Muda "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btnProducrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar8ActionPerformed
        FrmPesquisaVariedade dialog = new FrmPesquisaVariedade(cbVariedade);
    }//GEN-LAST:event_btnProducrar8ActionPerformed

    private void txtDataOrdemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataOrdemFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataOrdemFocusGained

    private void txtHoraOrdemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraOrdemFocusGained
        txtHoraOrdem.selectAll();
    }//GEN-LAST:event_txtHoraOrdemFocusGained

private void initMyComponents() throws SQLException {  
   
    this.btOk.setIcon(new ImageIcon("icons/check16.png"));
    this.btCancel.setIcon(new ImageIcon("icons/cancel16.png"));
   
    
   List<Safra> safra = new SafraDAO().getAllSafra();
   DefaultComboBoxModel dcbmSafra = new DefaultComboBoxModel(new Vector<Safra>(safra));
   cbSafra.setModel(dcbmSafra);  
   
   /*
   List<Fazenda> fazenda = new FazendaDAO().getAllFazenda();
   DefaultComboBoxModel dcbmFazenda = new DefaultComboBoxModel(new Vector<Fazenda>(fazenda));
   cbFazenda.setModel(dcbmFazenda);
   
   List<Setor> setor = new SetorDAO().getAllSetor();
   DefaultComboBoxModel dcbmSetor = new DefaultComboBoxModel(new Vector<Setor>(setor));
   cbSetor.setModel(dcbmSetor);
   
   List<Talhao> talhao = new TalhaoDAO().getAllTalhao();
   DefaultComboBoxModel dcbmTalhao = new DefaultComboBoxModel(new Vector<Talhao>(talhao));
   cbTalhao.setModel(dcbmTalhao);
   */
   
   cbTipoCorte.setModel(new DefaultComboBoxModel<>(TipoCorteQueima.values()));
   cbTipoColheita.setModel(new DefaultComboBoxModel<>(TipoPlantioColheita.values()));
   
   //List<Variedade> variedade = new VariedadeDAO().getAllVariedade();
   //DefaultComboBoxModel dcbmVariedade = new DefaultComboBoxModel(new Vector<Variedade>(variedade));
   //cbVariedade.setModel(dcbmVariedade);  
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar5;
    private javax.swing.JButton btnProducrar6;
    private javax.swing.JButton btnProducrar7;
    private javax.swing.JButton btnProducrar8;
    private javax.swing.JComboBox cbFazenda;
    private javax.swing.JComboBox cbSafra;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JComboBox cbTalhao;
    private javax.swing.JComboBox cbTipoColheita;
    private javax.swing.JComboBox cbTipoCorte;
    private javax.swing.JComboBox cbVariedade;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao10;
    private javax.swing.JLabel lblDescricao11;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    private javax.swing.JLabel lblDescricao9;
    private javax.swing.JFormattedTextField txtDataOrdem;
    private javax.swing.JFormattedTextField txtHoraOrdem;
    private javax.swing.JFormattedTextField txtQtdArea;
    private javax.swing.JFormattedTextField txtQtdEsti;
    // End of variables declaration//GEN-END:variables


}
