/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAddItemOfSell.java
 *
 * Created on Aug 20, 2008, 9:35:56 AM
 */

package br.com.agrofacil.frames;

import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.SafraDAO;
import br.com.agrofacil.dao.SetorDAO;
import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.entity.ApontamentoPlantioItem;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.Safra;
import br.com.agrofacil.entity.Setor;
import br.com.agrofacil.entity.Talhao;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dyego
 */
public class FrmAddApontamentoPlantioItem extends javax.swing.JDialog {

    private final List<ApontamentoPlantioItem> itens;
    private FrmAddApontamentoPlantio apontPlantioForm;
    private FrmUpdateApontamentoPlantio apontPlantioFormUp;
    
    private final SafraDAO safra = new SafraDAO();
    private final FazendaDAO fazenda = new FazendaDAO();
    private final SetorDAO setor = new SetorDAO();
    private final TalhaoDAO talhao = new TalhaoDAO();
    //private frmUpdateSell updateForm;
    /** Creates new form frmAddItemOfSell */
    public FrmAddApontamentoPlantioItem(java.awt.Frame parent, boolean modal,List<ApontamentoPlantioItem> itens,FrmAddApontamentoPlantio apontPlantioForm) throws SQLException {
        super(parent, modal);
        this.itens = itens;
        this.apontPlantioForm = apontPlantioForm;
        initComponents();
        loadComboData();
    }
    
    public FrmAddApontamentoPlantioItem(java.awt.Frame parent, boolean modal,List<ApontamentoPlantioItem> itens,FrmUpdateApontamentoPlantio apontPlantioFormUp) throws SQLException {
        super(parent, modal);
        this.itens = itens;
        this.apontPlantioFormUp = apontPlantioFormUp;
        initComponents();
        loadComboData();
    }    

    /*
    public FrmAddApontamentoInsumoItem(JFrame parent, boolean modal, List<ApontamentoInsumoItem> itens, frmUpdateSell updateForm) {
        super(parent, modal);
        this.itens = itens;
        this.updateForm = updateForm;
        initComponents();
        loadComboData();
    }
    * /

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lblDescricao5 = new javax.swing.JLabel();
        cbSafra = new javax.swing.JComboBox();
        lblDescricao6 = new javax.swing.JLabel();
        cbFazenda = new javax.swing.JComboBox();
        btnProducrar5 = new javax.swing.JButton();
        lblDescricao7 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox();
        btnProducrar6 = new javax.swing.JButton();
        lblDescricao8 = new javax.swing.JLabel();
        cbTalhao = new javax.swing.JComboBox();
        btnProducrar7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Item");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btOk.setText("Adicionar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblDescricao5.setText("Safra");

        lblDescricao6.setText("Fazenda");

        btnProducrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar5.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar5ActionPerformed(evt);
            }
        });

        lblDescricao7.setText("Setor");

        btnProducrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar6.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar6ActionPerformed(evt);
            }
        });

        lblDescricao8.setText("Talhao");

        btnProducrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar7.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescricao5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescricao7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblDescricao6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDescricao8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTalhao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao5)
                                .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricao6)
                                .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDescricao7)
                                    .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDescricao8)
                                    .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(569, 181));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        
        if (!validaCampos()) {
            return;
        }
        
        int opt = JOptionPane.showConfirmDialog(this,"Você tem Certeza ?","Adicionar Novo Item",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (opt == 0) {
            
        
           ApontamentoPlantioItem item = new ApontamentoPlantioItem();
           item.setSafra((Safra) cbSafra.getSelectedItem());           
           item.setFazenda((Fazenda) cbFazenda.getSelectedItem());           
           item.setSetor((Setor)cbSetor.getSelectedItem());
           item.setTalhao((Talhao)cbTalhao.getSelectedItem());
           itens.add(item);

           if (apontPlantioForm != null) {
               apontPlantioForm.refreshItens();
           } else {
               apontPlantioFormUp.refreshItens();
           }
           setVisible(false);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btnProducrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar5ActionPerformed
        FrmPesquisaFazenda dialog = new FrmPesquisaFazenda(cbFazenda);
    }//GEN-LAST:event_btnProducrar5ActionPerformed

    private void btnProducrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar6ActionPerformed
        FrmPesquisaSetor dialog = new FrmPesquisaSetor(cbSetor);
    }//GEN-LAST:event_btnProducrar6ActionPerformed

    private void btnProducrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar7ActionPerformed
        FrmPesquisaTalhao dialog = new FrmPesquisaTalhao(cbTalhao);
    }//GEN-LAST:event_btnProducrar7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar5;
    private javax.swing.JButton btnProducrar6;
    private javax.swing.JButton btnProducrar7;
    private javax.swing.JComboBox cbFazenda;
    private javax.swing.JComboBox cbSafra;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JComboBox cbTalhao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    // End of variables declaration//GEN-END:variables

    private void loadComboData() throws SQLException {        
           List<Safra> safra = new SafraDAO().getAllSafra();
           DefaultComboBoxModel dcbmSafra = new DefaultComboBoxModel(new Vector<Safra>(safra));
           cbSafra.setModel(dcbmSafra);
           
            /*           
           List<Fazenda> fazenda = new FazendaDAO().getAllFazenda();
           DefaultComboBoxModel dcbmFazenda = new DefaultComboBoxModel(new Vector<Fazenda>(fazenda));
           cbFazenda.setModel(dcbmFazenda);
           
           List<Setor> setor = new SetorDAO().getAllSetor();
           DefaultComboBoxModel dcbmSetor = new DefaultComboBoxModel(new Vector<Setor>(setor));
           cbSetor.setModel(dcbmSetor);
           
           List<Talhao> talhao = new TalhaoDAO().getAllTalhao();
           DefaultComboBoxModel dcbmTalhao = new DefaultComboBoxModel(new Vector<Talhao>(talhao));
           cbTalhao.setModel(dcbmTalhao);
           */
    }

    private boolean validaCampos() {
        if (cbFazenda.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Fazenda Não Selecionada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return false;
        } 

        if (cbSetor.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Setor Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return false;
        }        

        if (cbTalhao.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Talhao Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

}
