package br.com.agrofacil.frames;


import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.entity.Talhao;
import br.com.agrofacil.util.TableColumnAdjuster;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kelson
 */
public class FrmTalhao extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    
    private final TalhaoDAO dao = new TalhaoDAO();
    private List<Talhao> talhao = new LinkedList<>();
    private FrmPrincipal main;
    
    public FrmTalhao(FrmPrincipal main) throws SQLException {
        this.main = main;
        this.setTitle("Manutenção - Talhoes");
        this.setResizable(false);
        this.setClosable(false);
        this.setMaximizable(false);        
        initComponents();        
        initMyComponents();
        loadInitialData();
        
        //jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        
        //jTable1.setPreferredScrollableViewportSize(null);
        //jTable1.getColumnModel().getColumn(1).setPreferredWidth(120); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(400, 249));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btAtualizar)
                    .addComponent(btRemover)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed

        try {
            
            FrmAddTalhao dialog = new FrmAddTalhao( new javax.swing.JDesktopPane(), true,dao,this);    
            dialog.setVisible(true);
            dialog.setResizable(false);
            dialog.setClosable(false);        
            dialog.setMaximizable(false);        

            this.main.getDesktopPane().add(dialog);
               dialog.setMaximum(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmEquipamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmTalhao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
/*
        try {                                            
            // TODO add your handling code here:
            if(jTable1.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Selecione Fazenda para Editar");
                return;
            }

            FrmUpdateFazenda dialog = new FrmUpdateFazenda( new javax.swing.JDesktopPane(), true, fazenda.get(jTable1.getSelectedRow()),dao,  this);    
            dialog.setVisible(true);
            dialog.setResizable(false);
            dialog.setClosable(false);
            dialog.setMaximizable(false);        
                        
            this.main.getDesktopPane().add(dialog);
            dialog.setMaximum(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmEquipamento.class.getName()).log(Level.SEVERE, null, ex);
        } 
        */ 
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Escolha Talhao para Remover !!");
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "Você tem Certeza ??","Remover Talhao",JOptionPane.OK_CANCEL_OPTION);

        if(result != 0) {
            return;
        }
        try {
            try {
                dao.deleteTalhao(
                        talhao.get(jTable1.getSelectedRow()).getId());
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao Remover Talhao","Remover Talhao",JOptionPane.ERROR_MESSAGE);
            }
            loadInitialData();
        } catch (SQLException ex) {
            Logger.getLogger(FrmTalhao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

   public void loadInitialData() throws SQLException {
        
        List<String> columns = new ArrayList<String>();
        List<String[]> values = new ArrayList<String[]>();
        columns.add("Id");
        columns.add("Descrição");
        columns.add("Fazenda");
        columns.add("Setor");
        columns.add("Safra");
        columns.add("Frente Transporte");
        columns.add("Distancia Terra");
        columns.add("Distancia Asfalto");
        columns.add("Distancia Hidrovia");
        columns.add("Variedade");
        columns.add("Espacamento");
        columns.add("Qtd Area Prod");
        columns.add("Qtd Area Muda");
        columns.add("Empresa");
        columns.add("Unidade Industrial");
        columns.add("Data Situacao");
        columns.add("Situacao");
        
        talhao = dao.getAllTalhao();
        if (talhao.size() > 0) {
            for (int i = 0; i < talhao.size(); i++) {
                values.add(new String[] {String.valueOf(talhao.get(i).getId()), 
                talhao.get(i).getDescricao(),
                talhao.get(i).getFazenda().getDescricao(),
                talhao.get(i).getSetor().getDescricao(), 
                String.valueOf(talhao.get(i).getSafra().getId()),
                talhao.get(i).getFrenteTransporte().getDescricao(),
                String.valueOf(talhao.get(i).getDistTerra()),
                String.valueOf(talhao.get(i).getDistAsfalto()),
                String.valueOf(talhao.get(i).getDistHidrovia()),
                talhao.get(i).getVariedade().getDescricao(),
                talhao.get(i).getEspacamento().getDescricao(),
                String.valueOf(talhao.get(i).getQtdAreaProd()), 
                String.valueOf(talhao.get(i).getQtdAreaMuda()), 
                talhao.get(i).getEmpresa().getDescricao(),
                talhao.get(i).getUnidadeIndustrial().getDescricao(),
                String.valueOf(talhao.get(i).getDataSituacao()),                
                
                String.valueOf(talhao.get(i).getSituacao())});
            }               
        }                        
       TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
       jTable1.setModel(tableModel); 
      
       
       //for (int i = 0; i < columns.size(); i++) {
         // jTable1.getColumnModel().getColumn(i).setPreferredWidth(200); 
       //}
       
       jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTable1);
        //tca.setColumnDataIncluded(true);
        //tca.setOnlyAdjustLarger(true);
        tca.setDynamicAdjustment(true);
        
        tca.adjustColumns();
        //tca.adjustColumn(1);
 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
    private void initMyComponents() {
        this.btAdicionar.setIcon(new javax.swing.ImageIcon("icons/add2.png"));
        this.btAtualizar.setIcon(new javax.swing.ImageIcon("icons/edit.png"));
        this.btRemover.setIcon(new javax.swing.ImageIcon("icons/delete2.png"));
        this.btVoltar.setIcon(new javax.swing.ImageIcon("icons/exit.png"));
    }
}
