package br.com.agrofacil.frames;


import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.MunicipioDAO;
import br.com.agrofacil.entity.Empresa;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.Municipio;
import br.com.agrofacil.entity.TipoPessoa;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kelson
 */
public class FrmUpdateFazenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private final FazendaDAO dao;
    private final FrmFazenda control;
    private final Fazenda fazendaInEdit;
    private final MunicipioDAO municipioDAO = new MunicipioDAO();
    
    public FrmUpdateFazenda(javax.swing.JDesktopPane parent, boolean modal,Fazenda fazendaInEdit, FazendaDAO dao, FrmFazenda control) throws SQLException {             
        this.dao = dao;
        this.control = control;
        this.fazendaInEdit = fazendaInEdit;
        this.setTitle("Atualizar Fazenda");
        initComponents();
        initMyComponents();
        cbTipoPessoa.setModel(new DefaultComboBoxModel<>(TipoPessoa.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        cbMunicipio = new javax.swing.JComboBox();
        lblDescricao1 = new javax.swing.JLabel();
        btnProducrar = new javax.swing.JButton();
        txtEndereco = new javax.swing.JTextField();
        lblDescricao2 = new javax.swing.JLabel();
        lblDescricao3 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        lblDescricao4 = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JFormattedTextField();
        lblDescricao5 = new javax.swing.JLabel();
        txtInscIncra = new javax.swing.JFormattedTextField();
        lblDescricao6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblDescricao7 = new javax.swing.JLabel();
        lblDescricao8 = new javax.swing.JLabel();
        lblDescricao9 = new javax.swing.JLabel();
        cbFUnrual = new javax.swing.JComboBox();
        txtRazao = new javax.swing.JTextField();
        txtInscProd = new javax.swing.JFormattedTextField();
        lblDescricao10 = new javax.swing.JLabel();
        cbTipoPessoa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtAreaTot = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAreaProd = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAreaArrend = new javax.swing.JFormattedTextField();
        lblDescricao11 = new javax.swing.JLabel();
        txtImovel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAreaMat = new javax.swing.JFormattedTextField();
        lblDescricao12 = new javax.swing.JLabel();
        txtPesFis = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(400, 249));

        lblDescricao.setText("Descrição");

        btOk.setText("Atualizar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblDescricao1.setText("Municipio");

        btnProducrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrarActionPerformed(evt);
            }
        });

        lblDescricao2.setText("Endereco");

        lblDescricao3.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao4.setText("CPF/CNPJ");

        try {
            txtCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao5.setText("Inscricao INCRA");

        try {
            txtInscIncra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao6.setText("Telefone");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao7.setText("Inscricao Prod");

        lblDescricao8.setText("RazaoFundo");

        lblDescricao9.setText("Funrual");

        cbFUnrual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));

        try {
            txtInscProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao10.setText("Tipo Pessoa");

        cbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Area Tot");

        jLabel2.setText("Area Prod");

        jLabel3.setText("Area Arrend");

        lblDescricao11.setText("Imovel Receita");

        jLabel4.setText("Area Matricula");

        lblDescricao12.setText("CNPJ Pes Fisica");

        try {
            txtPesFis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblDescricao1)
                                    .addComponent(lblDescricao3)
                                    .addComponent(lblDescricao7))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricao)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInscProd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtRazao))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDescricao4)
                                                .addGap(30, 30, 30)
                                                .addComponent(txtCpfCnpj)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDescricao5)
                                                .addGap(16, 16, 16)
                                                .addComponent(txtInscIncra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDescricao6)
                                                .addGap(16, 16, 16)
                                                .addComponent(txtTelefone))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbFUnrual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAreaTot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAreaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAreaArrend, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(lblDescricao2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndereco)))))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescricao11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtAreaMat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescricao12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesFis, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addGap(278, 278, 278))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao1)
                        .addComponent(lblDescricao2)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao3)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao4)
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao5)
                    .addComponent(txtInscIncra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao6)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao7)
                    .addComponent(lblDescricao8)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInscProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao9)
                    .addComponent(cbFUnrual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao10)
                    .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtAreaTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAreaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtAreaArrend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao11)
                    .addComponent(txtImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAreaMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao12)
                    .addComponent(txtPesFis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {

            fazendaInEdit.setDescricao(txtDescricao.getText());
            fazendaInEdit.setMunicipio((Municipio)cbMunicipio.getSelectedItem());
            fazendaInEdit.setEndereco(txtEndereco.getText());
            fazendaInEdit.setTelefone(txtTelefone.getText());
            fazendaInEdit.setCpfcgc(txtCpfCnpj.getText());           
            fazendaInEdit.setInscricaoIncra(txtInscIncra.getText());
            fazendaInEdit.setInscricaoProdutor(txtInscProd.getText());
            fazendaInEdit.setCep(txtCep.getText());
            fazendaInEdit.setTipoPessoa(TipoPessoa.valueOf(cbTipoPessoa.getSelectedItem().toString()));
            if (cbFUnrual.getSelectedIndex() == 0) {
                fazendaInEdit.setFunrual(true);
            } else {
                fazendaInEdit.setFunrual(false);
            }
            fazendaInEdit.setAreaTotal(Float.parseFloat(txtAreaTot.getText()));
            fazendaInEdit.setAreaArrendamento(Float.parseFloat(txtAreaArrend.getText()));
            fazendaInEdit.setAreaProdutiva(Float.parseFloat(txtAreaProd.getText()));
            fazendaInEdit.setRazaoSocialFundo(txtRazao.getText());
            fazendaInEdit.setImovelReceita(txtImovel.getText());
            fazendaInEdit.setQtdAreaMat(Float.parseFloat(txtAreaMat.getText()));
            fazendaInEdit.setCnpjPesFis(txtPesFis.getText());
            
            dao.updateFazenda(fazendaInEdit);

            int result = JOptionPane.showConfirmDialog(this, "Você Tem Certeza ??","Atualizar Fazenda",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(result != 0) {
                return;
            }
            control.loadInitialData();
            setVisible(false);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar Fazenda "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btnProducrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrarActionPerformed
        FrmPesquisaMunicipio dialog = new FrmPesquisaMunicipio(cbMunicipio);         
    }//GEN-LAST:event_btnProducrarActionPerformed

private void initMyComponents() throws SQLException {  
   
    this.btOk.setIcon(new ImageIcon("icons/check16.png"));
    this.btCancel.setIcon(new ImageIcon("icons/cancel16.png"));
   
   List<Municipio> municipio = new MunicipioDAO().getAllMunicipio();
   DefaultComboBoxModel dcbm = new DefaultComboBoxModel(new Vector<Municipio>(municipio));
   cbMunicipio.setModel(dcbm);
   
   
   txtDescricao.setText(fazendaInEdit.getDescricao());
   cbMunicipio.setSelectedItem(fazendaInEdit.getMunicipio());
   txtEndereco.setText(fazendaInEdit.getEndereco());
   txtCpfCnpj.setText(fazendaInEdit.getCpfcgc());
   txtInscIncra.setText(fazendaInEdit.getInscricaoIncra());
   txtInscProd.setText(fazendaInEdit.getInscricaoProdutor());
   txtCep.setText(fazendaInEdit.getCep());
   cbTipoPessoa.setSelectedItem(TipoPessoa.valueOf(fazendaInEdit.getTipoPessoa().toString()));
   if (fazendaInEdit.isFunrual()== true) {
       cbFUnrual.setSelectedIndex(0);
   } else {
       cbFUnrual.setSelectedIndex(1);
   }
   txtAreaTot.setText(String.valueOf(fazendaInEdit.getAreaTotal()));
   txtAreaArrend.setText(String.valueOf(fazendaInEdit.getAreaArrendamento()));
   txtAreaProd.setText(String.valueOf(fazendaInEdit.getAreaProdutiva()));
   txtRazao.setText(fazendaInEdit.getRazaoSocialFundo());
   txtImovel.setText(fazendaInEdit.getImovelReceita());
   txtAreaMat.setText(String.valueOf(fazendaInEdit.getQtdAreaMat()));
   txtPesFis.setText(fazendaInEdit.getCnpjPesFis());
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar;
    private javax.swing.JComboBox cbFUnrual;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbTipoPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao10;
    private javax.swing.JLabel lblDescricao11;
    private javax.swing.JLabel lblDescricao12;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    private javax.swing.JLabel lblDescricao9;
    private javax.swing.JFormattedTextField txtAreaArrend;
    private javax.swing.JFormattedTextField txtAreaMat;
    private javax.swing.JFormattedTextField txtAreaProd;
    private javax.swing.JFormattedTextField txtAreaTot;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtImovel;
    private javax.swing.JFormattedTextField txtInscIncra;
    private javax.swing.JFormattedTextField txtInscProd;
    private javax.swing.JFormattedTextField txtPesFis;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables


}
