package br.com.agrofacil.frames;

import br.com.agrofacil.dao.ApontamentoPlantioDAO;
import br.com.agrofacil.dao.CentroCustoDAO;
import br.com.agrofacil.dao.EspacamentoDAO;
import br.com.agrofacil.dao.FazendaDAO;
import br.com.agrofacil.dao.OperacaoDAO;
import br.com.agrofacil.dao.OrdemCorteMudaDAO;
import br.com.agrofacil.dao.SafraDAO;
import br.com.agrofacil.dao.SetorDAO;
import br.com.agrofacil.dao.TalhaoDAO;
import br.com.agrofacil.dao.VariedadeDAO;
import br.com.agrofacil.entity.ApontamentoPlantio;
import br.com.agrofacil.entity.ApontamentoPlantioItem;
import br.com.agrofacil.entity.ApontamentoPlantioItem2;
import br.com.agrofacil.entity.CentroCusto;
import br.com.agrofacil.entity.Espacamento;
import br.com.agrofacil.entity.Fazenda;
import br.com.agrofacil.entity.Operacao;
import br.com.agrofacil.entity.OrdemCorteMuda;
import br.com.agrofacil.entity.Safra;
import br.com.agrofacil.entity.Setor;
import br.com.agrofacil.entity.Talhao;
import br.com.agrofacil.entity.TipoPlantioColheita;
import br.com.agrofacil.entity.Variedade;
import br.com.agrofacil.util.DateValidator;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Kelson
 */
public class FrmUpdateApontamentoPlantio extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private final ApontamentoPlantioDAO dao;
    private final FrmApontamentoPlantio control;
    private final ApontamentoPlantio apontamentoInEdit;
    private List<ApontamentoPlantioItem> itens = new LinkedList<ApontamentoPlantioItem>();
    private List<ApontamentoPlantioItem2> itens2 = new LinkedList<ApontamentoPlantioItem2>();    
    
    private final CentroCustoDAO centroDAO = new CentroCustoDAO();
    private final OperacaoDAO operacaoDAO = new OperacaoDAO();    
    private final VariedadeDAO variedadeDAO = new VariedadeDAO();    
    private final SafraDAO safraDAO = new SafraDAO();
    private final FazendaDAO fazendaDAO = new FazendaDAO();
    private final SetorDAO setorDAO = new SetorDAO();
    private final TalhaoDAO talhaoDAO = new TalhaoDAO();
    private final EspacamentoDAO espacamentoDAO = new EspacamentoDAO();
    
    public FrmUpdateApontamentoPlantio(javax.swing.JDesktopPane parent, boolean modal,ApontamentoPlantioDAO dao, FrmApontamentoPlantio control, ApontamentoPlantio apontamentoInEdit) throws SQLException {             
        this.dao = dao;
        this.control = control;
        this.setTitle("Atualizar Apontamento de Plantio");
        this.apontamentoInEdit = apontamentoInEdit;  
        itens = apontamentoInEdit.getItens();
        itens2 = apontamentoInEdit.getEquipamentos();
        initComponents();
        initMyComponents();
        refreshItens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbCentro = new javax.swing.JComboBox();
        lblDescricao1 = new javax.swing.JLabel();
        btnProducrar = new javax.swing.JButton();
        lblDescricao2 = new javax.swing.JLabel();
        cbOperacao = new javax.swing.JComboBox();
        btnProducrar1 = new javax.swing.JButton();
        lblDescricao4 = new javax.swing.JLabel();
        cbVariedade = new javax.swing.JComboBox();
        btnProducrar2 = new javax.swing.JButton();
        lblDescricao3 = new javax.swing.JLabel();
        cbEspacamento = new javax.swing.JComboBox();
        btnProducrar3 = new javax.swing.JButton();
        lblDescricao5 = new javax.swing.JLabel();
        cbSafra = new javax.swing.JComboBox();
        lblDescricao6 = new javax.swing.JLabel();
        cbFazenda = new javax.swing.JComboBox();
        btnProducrar5 = new javax.swing.JButton();
        lblDescricao7 = new javax.swing.JLabel();
        cbSetor = new javax.swing.JComboBox();
        btnProducrar6 = new javax.swing.JButton();
        lblDescricao8 = new javax.swing.JLabel();
        cbTalhao = new javax.swing.JComboBox();
        btnProducrar7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        cbTipoAplicacao = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtQtdProducao = new javax.swing.JFormattedTextField();
        lblDescricao9 = new javax.swing.JLabel();
        cbConcluido = new javax.swing.JComboBox();
        lblDescricao10 = new javax.swing.JLabel();
        txtDataPlantio = new javax.swing.JFormattedTextField();
        lblDescricao11 = new javax.swing.JLabel();
        cbReplantio = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtQtdEstimada = new javax.swing.JFormattedTextField();
        lblDescricao12 = new javax.swing.JLabel();
        cbOrdemCorteMuda = new javax.swing.JComboBox();
        btnProducrar4 = new javax.swing.JButton();
        txtQtdArea = new javax.swing.JFormattedTextField();
        txtDataFechamento = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btDeleteItem = new javax.swing.JButton();
        btAddItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItens2 = new javax.swing.JTable();
        btAddItem2 = new javax.swing.JButton();
        btDeleteItem2 = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 249));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Apontamento Insumo"));

        lblDescricao1.setText("Centro Custo");

        btnProducrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrarActionPerformed(evt);
            }
        });

        lblDescricao2.setText("Operacao");

        btnProducrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar1.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar1ActionPerformed(evt);
            }
        });

        lblDescricao4.setText("Variedade");

        btnProducrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar2.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar2ActionPerformed(evt);
            }
        });

        lblDescricao3.setText("Espacamento");

        btnProducrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar3.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar3ActionPerformed(evt);
            }
        });

        lblDescricao5.setText("Safra");

        lblDescricao6.setText("Fazenda");

        btnProducrar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar5.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar5ActionPerformed(evt);
            }
        });

        lblDescricao7.setText("Setor");

        btnProducrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar6.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar6ActionPerformed(evt);
            }
        });

        lblDescricao8.setText("Talhao");

        btnProducrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar7.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Qtd Area");

        lblDescricao.setText("DataFechamento:");

        txtTipo.setText("Tipo Aplicacao");

        cbTipoAplicacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAplicacaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Qtd Producao");

        txtQtdProducao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtQtdProducao.setText("0,00");
        txtQtdProducao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdProducaoMouseClicked(evt);
            }
        });
        txtQtdProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdProducaoActionPerformed(evt);
            }
        });
        txtQtdProducao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtdProducaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdProducaoFocusLost(evt);
            }
        });
        txtQtdProducao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQtdProducaoInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lblDescricao9.setText("Concluido ?");

        cbConcluido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));

        lblDescricao10.setText("Data Plantio:");

        try {
            txtDataPlantio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPlantio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataPlantioFocusGained(evt);
            }
        });

        lblDescricao11.setText("Replantio ?");

        cbReplantio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));

        jLabel8.setText("Qtd Estimada");

        txtQtdEstimada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtQtdEstimada.setText("0,00");
        txtQtdEstimada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdEstimadaMouseClicked(evt);
            }
        });
        txtQtdEstimada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtdEstimadaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdEstimadaFocusLost(evt);
            }
        });

        lblDescricao12.setText("Ordem Corte de Muda");

        btnProducrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agrofacil/util/icons/lupa16.png"))); // NOI18N
        btnProducrar4.setPreferredSize(new java.awt.Dimension(40, 25));
        btnProducrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducrar4ActionPerformed(evt);
            }
        });

        txtQtdArea.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtQtdArea.setText("0,00");
        txtQtdArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdAreaMouseClicked(evt);
            }
        });
        txtQtdArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdAreaActionPerformed(evt);
            }
        });
        txtQtdArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtdAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdAreaFocusLost(evt);
            }
        });

        try {
            txtDataFechamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFechamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataFechamentoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDescricao2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbOperacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDescricao1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbCentro, 0, 268, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDescricao7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescricao12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbOrdemCorteMuda, 0, 220, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescricao4)
                                .addGap(18, 18, 18)
                                .addComponent(cbVariedade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProducrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblDescricao6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTalhao, 0, 215, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbEspacamento, 0, 355, Short.MAX_VALUE)
                                            .addComponent(cbFazenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnProducrar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnProducrar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQtdEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescricao9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDescricao11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbReplantio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(150, 150, 150))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescricao10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdArea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProducrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao1)
                            .addComponent(cbCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao4)
                            .addComponent(cbVariedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnProducrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao2)
                        .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao3)
                        .addComponent(cbEspacamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao6)
                        .addComponent(cbFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao12)
                        .addComponent(cbOrdemCorteMuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducrar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao7)
                        .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProducrar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTalhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao8)
                        .addComponent(cbSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescricao5))
                    .addComponent(btnProducrar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblDescricao10)
                    .addComponent(txtDataPlantio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao9)
                    .addComponent(cbConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao11)
                    .addComponent(cbReplantio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtQtdProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        btDeleteItem.setText("Remover Item");
        btDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteItemActionPerformed(evt);
            }
        });

        btAddItem.setText("Adicionar Item");
        btAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddItemActionPerformed(evt);
            }
        });

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItens);

        tblItens2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblItens2);

        btAddItem2.setText("Adicionar Item");
        btAddItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddItem2ActionPerformed(evt);
            }
        });

        btDeleteItem2.setText("Remover Item");
        btDeleteItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteItem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btAddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDeleteItem))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAddItem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDeleteItem2)
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeleteItem)
                    .addComponent(btAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeleteItem2)
                    .addComponent(btAddItem2))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btOk.setText("Atualizar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancel)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOk))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducrar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar7ActionPerformed
        FrmPesquisaTalhao dialog = new FrmPesquisaTalhao(cbTalhao);
    }//GEN-LAST:event_btnProducrar7ActionPerformed

    private void btnProducrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar6ActionPerformed
        FrmPesquisaSetor dialog = new FrmPesquisaSetor(cbSetor);
    }//GEN-LAST:event_btnProducrar6ActionPerformed

    private void btnProducrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar5ActionPerformed
        FrmPesquisaFazenda dialog = new FrmPesquisaFazenda(cbFazenda);
    }//GEN-LAST:event_btnProducrar5ActionPerformed

    private void btnProducrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar3ActionPerformed
       FrmPesquisaEspacamento dialog = new FrmPesquisaEspacamento(cbEspacamento);
    }//GEN-LAST:event_btnProducrar3ActionPerformed

    private void btnProducrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar2ActionPerformed
        FrmPesquisaVariedade dialog = new FrmPesquisaVariedade(cbVariedade);
    }//GEN-LAST:event_btnProducrar2ActionPerformed

    private void btnProducrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar1ActionPerformed
        FrmPesquisaOperacao dialog = new FrmPesquisaOperacao(cbOperacao);
    }//GEN-LAST:event_btnProducrar1ActionPerformed

    private void btnProducrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrarActionPerformed
        try {
            FrmPesquisaCentroCusto dialog = new FrmPesquisaCentroCusto(cbCentro);
        } catch (SQLException ex) {
            Logger.getLogger(FrmUpdateApontamentoPlantio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProducrarActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        ApontamentoPlantio apont = new ApontamentoPlantio();
        DateValidator dateValidator = new DateValidator();
        
        
        if (txtQtdArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Quantidade Area Não Informada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }  
        
        if (txtQtdProducao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Quantidade Produção Não Informada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (txtQtdEstimada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Quantidade Estimada Não Informada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }        
           
        if (!validaValores()) {
            return;
        }
        
        if (cbCentro.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Centro de Custo Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cbVariedade.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Variedade Não Selecionada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cbOperacao.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Operação Não Selecionada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cbEspacamento.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Espacamento Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }        

        if (cbOrdemCorteMuda.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Ordem de Corte de Muda Não Selecionada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cbFazenda.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Fazenda Não Selecionada !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        if (cbSetor.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Setor Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }        
        
        if (cbTalhao.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Talhao Não Selecionado !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!dateValidator.isThisDateValid(txtDataFechamento.getText(),"dd/MM/yyyy")) {
            JOptionPane.showMessageDialog(this, "Data Fechamento Inválida !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;             
        }
        
        if (!dateValidator.isThisDateValid(txtDataPlantio.getText(),"dd/MM/yyyy")) {
            JOptionPane.showMessageDialog(this, "Data Plantio Inválida !","Alerta",JOptionPane.ERROR_MESSAGE);
            return;             
        }                 
                
        if (itens.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lista de Itens Vazia !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (itens2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lista de Equipamentos Vazia !","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            
            DateFormat dffrom = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataPlantio = new java.sql.Date(dffrom.parse(txtDataPlantio.getText()).getTime());
            java.sql.Date dataFechamento = new java.sql.Date(dffrom.parse(txtDataFechamento.getText()).getTime());

            apont.setId(apontamentoInEdit.getId());
            apont.setFazenda((Fazenda) cbFazenda.getSelectedItem());
            apont.setSetor((Setor) cbSetor.getSelectedItem());
            apont.setTalhao((Talhao) cbTalhao.getSelectedItem());
            apont.setDataPlantio(dataPlantio);
            apont.setDataFechamento(dataFechamento);
            apont.setTipoPlantio(TipoPlantioColheita.valueOf(cbTipoAplicacao.getSelectedItem().toString()));
            apont.setVariedade((Variedade) cbVariedade.getSelectedItem());
            apont.setEspacamento((Espacamento) cbEspacamento.getSelectedItem());
            apont.setQtdAreaPlantada(Float.parseFloat(txtQtdArea.getText().replace(",", ".")));
            apont.setQtdProducao(Float.parseFloat(txtQtdProducao.getText().replace(",", ".")));
            apont.setCentroCusto((CentroCusto) cbCentro.getSelectedItem());
            apont.setOperacao((Operacao) cbOperacao.getSelectedItem());
            apont.setSafra((Safra) cbSafra.getSelectedItem());
            apont.setTonEstimada(Float.parseFloat(txtQtdEstimada.getText().replace(",", ".")));
            //apont.setNumeroOrdem(Integer.parseInt(txtOrdem.getText()));
            apont.setOrdemCorteMuda((OrdemCorteMuda) cbOrdemCorteMuda.getSelectedItem());
                 
            if (cbConcluido.getSelectedIndex() == 0) {
                apont.setConcluido(true);
            } else {
                apont.setConcluido(false);
            }
            
            if (cbReplantio.getSelectedIndex() == 0) {
                apont.setPlantio(false);
            } else {
                apont.setPlantio(true);
            }
            
            apont.setItens(itens);
            apont.setEquipamentos(itens2);
            
            for (ApontamentoPlantioItem apontItens : itens) {
                apontItens.setApontamentoPlantio(apont);
            }
            
            for (ApontamentoPlantioItem2 apontItens2 : itens2) {
                apontItens2.setApontamentoPlantio(apont);
            }
                        
            int result = JOptionPane.showConfirmDialog(this, "Você Tem Certeza ??","Adicionar Apontamento de Plantio",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(result != 0) {
                return;
            }

            dao.updateApontamentoPlantio(apont);

            control.loadInitialData();
            setVisible(false);
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar Apontamento de Plantio "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddItemActionPerformed
       
        FrmAddApontamentoPlantioItem dialog;
        try {
            dialog = new FrmAddApontamentoPlantioItem(new javax.swing.JFrame(), true,itens,this);
            dialog.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmUpdateApontamentoPlantio.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btAddItemActionPerformed

    private void btDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteItemActionPerformed
        if (tblItens.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Item antes de Remover","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opt = JOptionPane.showConfirmDialog(this, "Você tem Certeza ?","Confirmar Deleção",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {
        itens.remove(tblItens.getSelectedRow());
        refreshItens();
        }
    }//GEN-LAST:event_btDeleteItemActionPerformed

    private void btAddItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddItem2ActionPerformed
        FrmAddApontamentoPlantioItem2 dialog;
        try {
            dialog = new FrmAddApontamentoPlantioItem2(new javax.swing.JFrame(), true,itens2,this);
            dialog.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmUpdateApontamentoPlantio.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btAddItem2ActionPerformed

    private void btDeleteItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteItem2ActionPerformed
                if (tblItens2.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Item antes de Remover","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opt = JOptionPane.showConfirmDialog(this, "Você tem Certeza ?","Confirmar Deleção",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {
        itens2.remove(tblItens2.getSelectedRow());
        refreshItens();
        }
    }//GEN-LAST:event_btDeleteItem2ActionPerformed

    private void cbTipoAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoAplicacaoActionPerformed

    private void txtQtdProducaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdProducaoFocusGained
        txtQtdProducao.selectAll();
    }//GEN-LAST:event_txtQtdProducaoFocusGained

    private void txtQtdEstimadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdEstimadaFocusGained
        txtQtdEstimada.selectAll();
    }//GEN-LAST:event_txtQtdEstimadaFocusGained

    private void txtDataPlantioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataPlantioFocusGained
        txtDataPlantio.selectAll();
    }//GEN-LAST:event_txtDataPlantioFocusGained

    private void btnProducrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducrar4ActionPerformed
        FrmPesquisaOrdemCorteMuda dialog = new FrmPesquisaOrdemCorteMuda(cbOrdemCorteMuda,cbSafra,cbFazenda,cbSetor,cbTalhao);
    }//GEN-LAST:event_btnProducrar4ActionPerformed

    private void txtQtdProducaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdProducaoFocusLost

    }//GEN-LAST:event_txtQtdProducaoFocusLost

    private void txtQtdEstimadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdEstimadaFocusLost

    }//GEN-LAST:event_txtQtdEstimadaFocusLost

    private void txtQtdProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdProducaoActionPerformed
        txtQtdProducao.selectAll();
    }//GEN-LAST:event_txtQtdProducaoActionPerformed

    private void txtQtdAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdAreaActionPerformed

    private void txtQtdAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdAreaFocusGained
        txtQtdArea.selectAll();
    }//GEN-LAST:event_txtQtdAreaFocusGained

    private void txtQtdAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdAreaFocusLost

    }//GEN-LAST:event_txtQtdAreaFocusLost

    private void txtQtdAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdAreaMouseClicked
        txtQtdArea.selectAll();
    }//GEN-LAST:event_txtQtdAreaMouseClicked

    private void txtQtdProducaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdProducaoMouseClicked
        txtQtdProducao.selectAll();
    }//GEN-LAST:event_txtQtdProducaoMouseClicked

    private void txtQtdProducaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtdProducaoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdProducaoInputMethodTextChanged

    private void txtQtdEstimadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdEstimadaMouseClicked
        txtQtdEstimada.selectAll();
    }//GEN-LAST:event_txtQtdEstimadaMouseClicked

    private void txtDataFechamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFechamentoFocusGained
        txtDataFechamento.selectAll();
    }//GEN-LAST:event_txtDataFechamentoFocusGained

    private boolean validaValores() {
        boolean retorno = true;
                
        if (Float.parseFloat(txtQtdProducao.getText().replace(",", ".")) > Float.parseFloat(txtQtdArea.getText().replace(",", "."))) {
            JOptionPane.showMessageDialog(this, "Quantidade de Producao deve ser menor que Quantidade da Area !","Error",JOptionPane.ERROR_MESSAGE);
            retorno = false;             
        } else if (Float.parseFloat(txtQtdEstimada.getText().replace(",", ".")) > Float.parseFloat(txtQtdArea.getText().replace(",", "."))) {
            JOptionPane.showMessageDialog(this,  "Quantidade Estimada deve ser menor que Quantidade da Area !","Error",JOptionPane.ERROR_MESSAGE);            
            retorno = false;             
        }        
        
        return retorno;
    }
private void initMyComponents() throws SQLException {  
   
    this.btOk.setIcon(new ImageIcon("icons/check16.png"));
    this.btCancel.setIcon(new ImageIcon("icons/cancel16.png"));

   List<Safra> safraLista = new LinkedList<>();
   Safra safra = new SafraDAO().getSafra(apontamentoInEdit.getSafra().getId());
   safraLista.add(safra);   
   DefaultComboBoxModel dcbmSafra = new DefaultComboBoxModel(new Vector<Safra>(safraLista));
   cbSafra.setModel(dcbmSafra);  
   cbSafra.setSelectedItem(apontamentoInEdit.getSafra());

   List<Fazenda> fazendaLista = new LinkedList<>();
   Fazenda fazenda = new FazendaDAO().getFazenda(apontamentoInEdit.getFazenda().getId());
   fazendaLista.add(fazenda);
   DefaultComboBoxModel dcbmFazenda = new DefaultComboBoxModel(new Vector<Fazenda>(fazendaLista));
   cbFazenda.setModel(dcbmFazenda);
   
   List<Setor> setorLista = new LinkedList<>();
   Setor setor = new SetorDAO().getSetor(apontamentoInEdit.getSetor().getId());
   setorLista.add(setor);
   DefaultComboBoxModel dcbmSetor = new DefaultComboBoxModel(new Vector<Setor>(setorLista));
   cbSetor.setModel(dcbmSetor);
   
   List<Talhao> talhaoLista = new LinkedList<>();
   Talhao talhao = new TalhaoDAO().getTalhao(apontamentoInEdit.getTalhao().getId());
   talhaoLista.add(talhao);
   DefaultComboBoxModel dcbmTalhao = new DefaultComboBoxModel(new Vector<Talhao>(talhaoLista));
   cbTalhao.setModel(dcbmTalhao);  
   
   List<Variedade> variedadeLista = new LinkedList<>();
   Variedade variedade = new VariedadeDAO().getVariedade(apontamentoInEdit.getVariedade().getId());
   variedadeLista.add(variedade);
   DefaultComboBoxModel dcbmVariedade = new DefaultComboBoxModel(new Vector<Variedade>(variedadeLista));
   cbVariedade.setModel(dcbmVariedade);  
   
   List<Espacamento> espacamentoLista = new LinkedList<>();
   Espacamento espacamento = new EspacamentoDAO().getEspacamento(apontamentoInEdit.getEspacamento().getId());
   espacamentoLista.add(espacamento);
   DefaultComboBoxModel dcbmEspacamento = new DefaultComboBoxModel(new Vector<Espacamento>(espacamentoLista));
   cbEspacamento.setModel(dcbmEspacamento);    
   
   List<CentroCusto> centroLista = new LinkedList<>();
   CentroCusto centro = new CentroCustoDAO().getCentroCusto(apontamentoInEdit.getCentroCusto().getId());
   centroLista.add(centro);
   DefaultComboBoxModel dcbmCentro = new DefaultComboBoxModel(new Vector<CentroCusto>(centroLista)); 
   cbCentro.setModel(dcbmCentro); 
  
   List<Operacao> operacaoLista = new LinkedList<>();
   Operacao operacao = new OperacaoDAO().getOperacao(apontamentoInEdit.getOperacao().getId());
   operacaoLista.add(operacao);
   DefaultComboBoxModel dcbmOperacao = new DefaultComboBoxModel(new Vector<Operacao>(operacaoLista));
   cbOperacao.setModel(dcbmOperacao);   
   
   List<OrdemCorteMuda> ordemLista = new LinkedList<>();
   OrdemCorteMuda ordemCorteMuda = new OrdemCorteMudaDAO().getOrdemCorteMuda(apontamentoInEdit.getOrdemCorteMuda().getId());
   ordemLista.add(ordemCorteMuda);
   DefaultComboBoxModel dcbmOrdem = new DefaultComboBoxModel(new Vector<OrdemCorteMuda>(ordemLista));
   cbOrdemCorteMuda.setModel(dcbmOrdem);    
   
   SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");     
   txtDataPlantio.setText(df.format(apontamentoInEdit.getDataPlantio()));
   txtDataFechamento.setText(df.format(apontamentoInEdit.getDataFechamento()));
   
   txtQtdArea.setText(String.valueOf(apontamentoInEdit.getQtdAreaPlantada()).replace('.', ','));
   txtQtdProducao.setText(String.valueOf(apontamentoInEdit.getQtdProducao()).replace('.', ','));
   txtQtdEstimada.setText(String.valueOf(apontamentoInEdit.getTonEstimada()).replace('.', ','));
   
   cbTipoAplicacao.setModel(new DefaultComboBoxModel(TipoPlantioColheita.values()));
   cbTipoAplicacao.setSelectedItem(apontamentoInEdit.getTipoPlantio());
   
    if (apontamentoInEdit.getConcluido()) {
        cbConcluido.setSelectedIndex(0);
    } else {
        cbConcluido.setSelectedIndex(1);
    }   
    
    if (apontamentoInEdit.getPlantio()) {
        cbReplantio.setSelectedIndex(0);
    } else {
        cbReplantio.setSelectedIndex(1);
    }
}    

    public void refreshItens() {
        tblItens.setModel(new MyTableModel(ApontamentoPlantioItem.class, itens, tblItens));
        tblItens2.setModel(new MyTableModel(ApontamentoPlantioItem2.class, itens2, tblItens2));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddItem;
    private javax.swing.JButton btAddItem2;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDeleteItem;
    private javax.swing.JButton btDeleteItem2;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btnProducrar;
    private javax.swing.JButton btnProducrar1;
    private javax.swing.JButton btnProducrar2;
    private javax.swing.JButton btnProducrar3;
    private javax.swing.JButton btnProducrar4;
    private javax.swing.JButton btnProducrar5;
    private javax.swing.JButton btnProducrar6;
    private javax.swing.JButton btnProducrar7;
    private javax.swing.JComboBox cbCentro;
    private javax.swing.JComboBox cbConcluido;
    private javax.swing.JComboBox cbEspacamento;
    private javax.swing.JComboBox cbFazenda;
    private javax.swing.JComboBox cbOperacao;
    private javax.swing.JComboBox cbOrdemCorteMuda;
    private javax.swing.JComboBox cbReplantio;
    private javax.swing.JComboBox cbSafra;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JComboBox cbTalhao;
    private javax.swing.JComboBox cbTipoAplicacao;
    private javax.swing.JComboBox cbVariedade;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao10;
    private javax.swing.JLabel lblDescricao11;
    private javax.swing.JLabel lblDescricao12;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblDescricao8;
    private javax.swing.JLabel lblDescricao9;
    private javax.swing.JTable tblItens;
    private javax.swing.JTable tblItens2;
    private javax.swing.JFormattedTextField txtDataFechamento;
    private javax.swing.JFormattedTextField txtDataPlantio;
    private javax.swing.JFormattedTextField txtQtdArea;
    private javax.swing.JFormattedTextField txtQtdEstimada;
    private javax.swing.JFormattedTextField txtQtdProducao;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables


}
